version: '2.1'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 9080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    restart: on-failure
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
  consul:
    container_name: consul
    image: consul
    restart: on-failure
    ports:
      - "8500:8500"
    #volumes:
    #    - ./consul-volume/data:/consul/data
    #    - ./consul-volume/config:/consul/config
  mongodb:
    container_name: mongodb
    image: 'mongo:4.4.3'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 250977cc
    ports:
      - 27017-27021:27017-27021
    volumes:
      - ./volumes/mongo:/data/liquibase

  customer-service:
    container_name: customer-service
    build:
      context: ../services/customer-service/
      dockerfile: ../customer-service/Dockerfile
    image: customer-service05:latest
    depends_on:
      - mongodb
      - jaeger
      - consul
    environment:
      SERVER_PORT: 8081
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      JAEGER_HOST: http://jaeger
      JAEGER_PORT: 14250
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    ports:
      - "127.0.0.1:8081:8081"
  pet-clinic-service:
    container_name: pet-clinic-service
    build:
      context: ../services/pet-clinic-service
      dockerfile: ../pet-clinic-service/Dockerfile
    image: pet-clinic-service04:latest
    depends_on:
      - mongodb
      - jaeger
      - consul
    environment:
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      JAEGER_HOST: http://jaeger
      JAEGER_PORT: 14250
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    ports:
      - "127.0.0.1:8082:8082"

  pet-service:
    container_name: pet-service
    build:
      context: ../services/pet-service
      dockerfile: ../pet-service/Dockerfile
    image: pet-service:latest
    depends_on:
      - mongodb
      - jaeger
      - consul
    environment:
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      JAEGER_HOST: http://jaeger
      JAEGER_PORT: 14250
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    network_mode: host
    ports:
      - "127.0.0.1:8083:8083"

  treatment-service:
    container_name: treatment-service
    build:
      context: ../services/treatment-service
      dockerfile: ../treatment-service/Dockerfile
    image: treatment-service:latest
    depends_on:
      - mongodb
      - jaeger
      - consul
    environment:
      SERVER_PORT: 8084
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      JAEGER_HOST: http://jaeger
      JAEGER_PORT: 14250
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
